# Generated by Django 5.2.4 on 2025-09-03 19:09

import conferences.models
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('orgnizations', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('summary', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('research_topic', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('raw_file', models.FileField(blank=True, help_text='PDF file stored in MinIO', null=True, storage=storages.backends.s3.S3Storage(), upload_to=conferences.models.publication_file_path)),
                ('tag', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('pdf_url', models.CharField(max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='conferences.instance')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('transcript', models.TextField()),
                ('expert_view', models.TextField()),
                ('ai_analysis', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conferences.instance')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='conferences.publication')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='conferences.venue'),
        ),
    ]
