# Generated by Django 5.2.4 on 2025-10-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotebookChatMessage',
        ),
    ]
