# Generated by Django 5.2.4 on 2025-09-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebaseitem',
            name='notebook',
            field=models.ForeignKey(help_text='Notebook this knowledge item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_items', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='notebook',
            field=models.ForeignKey(help_text='Notebook this chat session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='notebook',
            field=models.ForeignKey(help_text='Notebook this batch job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='notebookchatmessage',
            name='notebook',
            field=models.ForeignKey(help_text='Notebook this chat message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='sessionchatmessage',
            name='notebook',
            field=models.ForeignKey(help_text='Notebook this chat message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='session_chat_messages', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='sessionchatmessage',
            name='session',
            field=models.ForeignKey(help_text='Chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notebooks.chatsession'),
        ),
        migrations.AddIndex(
            model_name='batchjobitem',
            index=models.Index(fields=['batch_job', 'status'], name='notebooks_b_batch_j_1526f0_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjobitem',
            index=models.Index(fields=['batch_job', 'created_at'], name='notebooks_b_batch_j_536e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjobitem',
            index=models.Index(fields=['upload_id'], name='notebooks_b_upload__cb0898_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['knowledge_base_item', 'created_at'], name='notebooks_k_knowled_01b34a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['minio_object_key'], name='notebooks_k_minio_o_bcbe25_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['figure_id'], name='notebooks_k_figure__1780d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebaseimage',
            constraint=models.CheckConstraint(condition=models.Q(('minio_object_key', ''), _negated=True), name='image_object_key_not_empty'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['user', '-created_at'], name='notebooks_n_user_id_85ff82_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['user', 'name'], name='notebooks_n_user_id_c83685_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebook',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_notebook_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['notebook', '-created_at'], name='notebooks_k_noteboo_a2cd57_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['notebook', 'parsing_status'], name='notebooks_k_noteboo_14d6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['notebook', 'content_type'], name='notebooks_k_noteboo_74218b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['notebook', 'source_hash'], name='notebooks_k_noteboo_fd687d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['file_object_key'], name='notebooks_k_file_ob_b76e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['original_file_object_key'], name='notebooks_k_origina_939f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['ragflow_document_id'], name='notebooks_k_ragflow_a2c381_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['notebook', 'ragflow_processing_status'], name='notebooks_k_noteboo_43feb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='knowledge_item_title_not_empty'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['notebook', 'status', '-last_activity'], name='notebooks_c_noteboo_be7fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='notebooks_c_session_6f1dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['ragflow_session_id'], name='notebooks_c_ragflow_a3d39a_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('ragflow_session_id__isnull', False)), fields=('notebook', 'ragflow_session_id'), name='unique_ragflow_session_per_notebook'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['notebook', '-created_at'], name='notebooks_b_noteboo_03c780_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['notebook', 'status'], name='notebooks_b_noteboo_768522_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['notebook', 'job_type'], name='notebooks_b_noteboo_149a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['status', '-created_at'], name='notebooks_b_status_424cec_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchjob',
            constraint=models.CheckConstraint(condition=models.Q(('total_items__gte', 0)), name='batch_job_total_items_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='batchjob',
            constraint=models.CheckConstraint(condition=models.Q(('completed_items__gte', 0)), name='batch_job_completed_items_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='batchjob',
            constraint=models.CheckConstraint(condition=models.Q(('failed_items__gte', 0)), name='batch_job_failed_items_non_negative'),
        ),
        migrations.AddIndex(
            model_name='notebookchatmessage',
            index=models.Index(fields=['notebook', 'timestamp'], name='notebooks_n_noteboo_7e61d9_idx'),
        ),
        migrations.AddIndex(
            model_name='notebookchatmessage',
            index=models.Index(fields=['notebook', 'sender', 'timestamp'], name='notebooks_n_noteboo_4587d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebookchatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='chat_message_not_empty'),
        ),
        migrations.AddIndex(
            model_name='sessionchatmessage',
            index=models.Index(fields=['session', 'message_order'], name='notebooks_s_session_0e9713_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionchatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='notebooks_s_session_98ca68_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionchatmessage',
            index=models.Index(fields=['notebook', 'timestamp'], name='notebooks_s_noteboo_8bd98e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionchatmessage',
            index=models.Index(fields=['sender', 'timestamp'], name='notebooks_s_sender_f87357_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionchatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='session_chat_message_not_empty'),
        ),
    ]
