panel_discussion_task:
  description: >
    主持 {topic} 与 {material_content} 的专题讨论，产出一份从开场到收束的完整面板讨论语音记录，
    通过真实的问答与交互引导听众理解技术本质与实践价值。
    
    **核心约束：**
    - 严格锚定 topic 与 material_content，全程多次引用具体内容（至少3处关键引用），无需每轮都引用
    - 使用 Ask question to coworker 工具，专家限定：伊利亚、崔道、李飞飞、一龙
    - 轮次自适应，以讨论"完整性与清晰度"为准（层层递进、自然收束）
    
    **长度与深度要求（关键指标）：**
    - 讨论总长度必须控制在10000-15000字符范围内
    - 如果生成内容少于8000字符，主持人必须主动延续和深化讨论
    - 每个核心技术点至少需要3轮深入交流（问题-回答-追问-深化）
    - 专家单次回答长度建议200-600字符，根据复杂度调整
    - 确保有真实的专家间观点碰撞和交叉讨论
    
    **主持人自主权：**
    - 自由分配讨论轮次和互动顺序
    - 根据内容深度选择最合适的专家参与
    - 灵活调整讨论节奏：深挖→整合→洞察→总结
    - 控场节奏把握：适时追问、转场与收束；打断有度，确保连贯与聚焦
    - **长度监控责任**: 持续监控讨论长度，未达标时主动延续讨论
    
    **专家要求：**
    - 结论先行，口语化表达，提供具体技术细节/数据/方案（长度自适应）
    - 承接前述讨论，回应与追问自然，深化技术内容
    - **深度要求**: 避免浅层回答，每次回应都要包含具体技术细节或实践洞察
    - **自然交流**: 可以对其他专家的观点进行回应、质疑或补充
    
    **表达风格（自然度优化）：**
    - 自然对话：口头语、思考痕迹、术语口语化、个性化表达
    - 句长多样，避免模板化，长度自适应
    - 真实停顿：适当的"嗯"、"那个"、"实际上"等连接词
    - 思维过程：展现思考轨迹，如"让我想想"、"换个角度说"
    - 发言仅包含"可被听到的口语内容"，不输出Markdown、列表、编号、表情、括号内提示或舞台说明
    

  expected_output: >
    [雷克思] 开场欢迎与主题引入；简要介绍嘉宾与议程。
    [专家名] 自我介绍（可一句带过；若已出现可省略）。
    [雷克思] 针对话题的具体问题...
    [专家名] 详细回答与技术分析...
    ... 多轮问答/讨论，明确说话人，逐步推进关键议题 ...
    [雷克思] 收束总结：关键结论、适用边界与下一步行动。

    要求：
    - 使用 [说话人] 内容 格式，每个发言独占一行
    - 发言内容为可直接TTS的口语文本，不含Markdown、列表、编号、表情或舞台说明
    - 讨论紧扣 topic 与 material_content，关键处引用具体内容（全程≥3处），但避免机械重复
    - 交互真实自然：有回应、有追问、有分歧也有整合，最终形成清晰结论或建议

  agent: moderator

polish_transcript_task:
  description: >
    对讨论记录进行语言润色，使表达更自然流畅，同时严格保持原有信息内容和技术观点不变。
    
    **润色原则（关键约束）：**
    - **内容不变**: 绝对不能修改、删除或添加任何技术信息、观点或结论
    - **信息完整**: 保持所有专家的发言内容和逻辑完整性
    - **观点保真**: 不能改变任何专家的技术立场或判断
    
    **语言优化重点：**
    - **口语化调整**: 将生硬的书面语转换为自然口语表达
    - **连接优化**: 优化句子间的自然连接，避免突兀转折
    - **TTS适配**: 去除特殊符号，优化标点符号以适配语音播放
    - **语感提升**: 适度添加口语停顿词"嗯"、"那个"、"实际上"等
    - **节奏调整**: 优化句子长短搭配，符合自然说话节奏
    
    **严格禁止的操作：**
    - 不能增加或删除技术细节
    - 不能改变专家的核心观点
    - 不能修改讨论的逻辑结构
    - 不能调整对话的长度或深度
    - 不能改变材料引用的具体内容

  expected_output: >
    [雷克思] 润色后的开场内容...
    [专家名] 润色后的专家发言...
    [雷克思] 润色后的主持人回应...
    ... 保持原有对话结构，仅优化语言表达 ...
    
    要求：使用 [说话人] 内容 格式，每个发言独占一行，语言自然，保持原意，TTS友好，技术内容完全不变

  agent: conversation_optimizer