"""
Schema Definitions for Coordinator

This module defines the task descriptions, input/output schemas,
and agent capability definitions used by the coordinator.
"""

from typing import Any
from enum import Enum
from pydantic import BaseModel, Field


# ============================================================================
# ENUMS
# ============================================================================


class TaskType(str, Enum):
    """Types of tasks the coordinator can execute."""

    RESEARCH_ONLY = "research_only"
    WRITE_ONLY = "write_only"
    RESEARCH_AND_WRITE = "research_and_write"


class TaskStatus(str, Enum):
    """Status of a task execution."""

    PENDING = "pending"
    CLARIFYING = "clarifying"
    PLANNING = "planning"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"


# ============================================================================
# CLARIFICATION SCHEMAS
# ============================================================================


class ClarificationQuestion(BaseModel):
    """A clarification question to ask the user."""

    question: str = Field(description="The question to ask")
    purpose: str = Field(description="Why this information is needed")
    required: bool = Field(default=True, description="Whether this is required")


class ClarificationResult(BaseModel):
    """Result of a clarification round."""

    need_clarification: bool = Field(description="Whether more clarification is needed")
    questions: list[ClarificationQuestion] = Field(
        default_factory=list, description="Questions to ask if clarification needed"
    )
    confident: bool = Field(
        default=False, description="Whether the coordinator is confident to proceed"
    )
    extracted_requirements: dict[str, Any] = Field(
        default_factory=dict, description="Requirements extracted from conversation"
    )
    verification_message: str = Field(
        default="", description="Message confirming understanding if confident"
    )


# ============================================================================
# TASK SCHEMAS
# ============================================================================


class TaskOptions(BaseModel):
    """Options for task execution."""

    task_type: TaskType | None = Field(
        default=None, description="Type of task to execute. If None, auto-detected."
    )
    style: str = Field(default="academic", description="Writing style for reports")
    max_research_iterations: int | None = Field(
        default=None, description="Max research iterations"
    )
    timeout: float | None = Field(
        default=None, description="Overall timeout in seconds"
    )
    language: str | None = Field(default=None, description="Preferred output language")
    skip_clarification: bool = Field(
        default=False, description="Skip clarification phase"
    )


class TaskStep(BaseModel):
    """A single step in the execution plan."""

    step_id: str = Field(description="Unique step identifier")
    agent_name: str = Field(description="Agent to execute this step")
    action: str = Field(description="Action description")
    inputs: dict[str, Any] = Field(
        default_factory=dict, description="Input parameters for the agent"
    )
    depends_on: list[str] = Field(
        default_factory=list, description="Step IDs this step depends on"
    )


class TaskPlan(BaseModel):
    """Execution plan generated by the coordinator."""

    task_id: str = Field(description="Unique task identifier")
    task_type: TaskType = Field(description="Type of task")
    steps: list[TaskStep] = Field(
        default_factory=list, description="Ordered list of execution steps"
    )
    parallel_groups: list[list[str]] = Field(
        default_factory=list, description="Groups of step IDs that can run in parallel"
    )
    estimated_duration: float | None = Field(
        default=None, description="Estimated duration in seconds"
    )


class ExecutionLog(BaseModel):
    """Log entry for task execution."""

    step_id: str = Field(description="Step being executed")
    agent_name: str = Field(description="Agent executing")
    status: str = Field(description="Step status")
    duration_ms: float | None = Field(default=None)
    message: str | None = Field(default=None)
    error: str | None = Field(default=None)


class TaskResult(BaseModel):
    """Result of task execution."""

    task_id: str = Field(description="Task identifier")
    status: TaskStatus = Field(description="Final task status")
    plan: TaskPlan | None = Field(default=None, description="Execution plan")
    execution_logs: list[ExecutionLog] = Field(
        default_factory=list, description="Execution logs"
    )

    # Research output (if applicable)
    findings: str | None = Field(default=None, description="Research findings")
    sources: list[dict[str, Any]] = Field(
        default_factory=list, description="Research sources"
    )

    # Report output (if applicable)
    final_report: str | None = Field(default=None, description="Generated report")

    # Metadata
    total_duration_ms: float | None = Field(default=None)
    error_message: str | None = Field(default=None)


# ============================================================================
# AGENT CAPABILITY SCHEMAS
# ============================================================================


class AgentCapability(BaseModel):
    """Describes what an agent can do."""

    name: str = Field(description="Agent name")
    description: str = Field(description="What this agent does")
    input_fields: list[str] = Field(description="Required input field names")
    output_fields: list[str] = Field(description="Output field names")


# Define capabilities for our agents
RESEARCH_AGENT_CAPABILITY = AgentCapability(
    name="research",
    description="Performs deep web research on a topic, gathering sources and synthesizing findings",
    input_fields=["topic", "max_depth", "max_iterations", "timeout"],
    output_fields=["findings", "sources", "raw_notes", "research_brief"],
)

WRITER_AGENT_CAPABILITY = AgentCapability(
    name="writer",
    description="Generates polished reports from research findings",
    input_fields=["research_brief", "findings", "sources", "style", "draft_outline"],
    output_fields=["final_report", "sections", "word_count", "language"],
)
