# Generated by Django 5.2.4 on 2025-09-18 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(default='Panel Conversation', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('custom_instruction', models.TextField(blank=True, help_text='Custom discussion instruction', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('status_message', models.TextField(default='Job queued for processing')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for generated audio file', max_length=255, null=True)),
                ('file_metadata', models.JSONField(default=dict, help_text='Audio file metadata (filename, size, duration, etc.)')),
                ('conversation_text', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_file_ids', models.JSONField(default=list)),
                ('source_metadata', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Generated podcast result data')),
                ('notebook', models.ForeignKey(help_text='Associated notebook (required)', on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='notebooks.notebook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='podcast_pod_status_5de595_idx'), models.Index(fields=['user', 'created_at'], name='podcast_pod_user_id_ec4ead_idx'), models.Index(fields=['audio_object_key'], name='podcast_pod_audio_o_359513_idx')],
            },
        ),
    ]
