# Generated by Django 5.2.4 on 2025-09-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcast', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['status'], name='podcast_pod_status_5de595_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['user', 'created_at'], name='podcast_pod_user_id_ec4ead_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['audio_object_key'], name='podcast_pod_audio_o_359513_idx'),
        ),
    ]
